module.exports = {}

module.exports.items = {
	'abacus': {name: 'Abacus', cost: '2 gp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'acid': {name: 'Acid (vial)', cost: '25 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'alchemists fire': {name: 'Alchemist\'s fire (flask)', cost: '50 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'ammunition, arrows': {name: 'Ammunition, Arrows (20)', cost: '1 gp ', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'ammunition, blowgun needles': {name: 'Ammunition, Blowgun needles (50)', cost: '1 gp ', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'ammunition, crossbow bolts': {name: 'Ammunition, Crossbow bolts (20)', cost: '1 gp ', weight: '1 1/2 lb.', rarity: 'common', type: 'adventuring gear'},
	'ammunition, sling bullets': {name: 'Ammunition, Sling bullets (20)', cost: '4 cp ', weight: '1 1/2 lb.', rarity: 'common', type: 'adventuring gear'},
	'antitoxin': {name: 'Antitoxin (vial)', cost: '50 gp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'arcane focus, crystal': {name: 'Arcane Focus, Crystal', cost: '10 gp ', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'arcane focus, orb': {name: 'Arcane Focus, Orb', cost: '20 gp ', weight: '3 lb.', rarity: 'common', type: 'adventuring gear'},
	'arcane focus, rod': {name: 'Arcane Focus, Rod', cost: '10 gp ', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'arcane focus, staff': {name: 'Arcane Focus, Staff', cost: '5 gp ', weight: '4 lb.', rarity: 'common', type: 'adventuring gear'},
	'arcane focus, wand': {name: 'Arcane Focus, Wand', cost: '10 gp ', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'backpack': {name: 'Backpack', cost: '2 gp', weight: '5 lb.', rarity: 'common', type: 'adventuring gear'},
	'ball bearings': {name: 'Ball bearings (bag of 1,000)', cost: '1 gp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'barrel': {name: 'Barrel', cost: '2 gp', weight: '70 lb.', rarity: 'common', type: 'adventuring gear'},
	'basket': {name: 'Basket', cost: '4 sp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'bedroll': {name: 'Bedroll', cost: '1 gp', weight: '7 lb.', rarity: 'common', type: 'adventuring gear'},
	'bell': {name: 'Bell', cost: '1 gp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'blanket': {name: 'Blanket', cost: '5 sp', weight: '3 lb.', rarity: 'common', type: 'adventuring gear'},
	'block and tackle': {name: 'Block and tackle', cost: '1 gp', weight: '5 lb.', rarity: 'common', type: 'adventuring gear'},
	'book': {name: 'Book', cost: '25 gp', weight: '5 lb.', rarity: 'common', type: 'adventuring gear'},
	'bottle, glass': {name: 'Bottle, glass', cost: '2 gp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'bucket': {name: 'Bucket', cost: '5 cp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'caltrops': {name: 'Caltrops (bag of 20)', cost: '1 gp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'candle': {name: 'Candle', cost: '1 cp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'case, crossbow bolt': {name: 'Case, crossbow bolt', cost: '1 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'case, map or scroll': {name: 'Case, map or scroll', cost: '1 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'chain': {name: 'Chain (10 feet)', cost: '5 gp', weight: '10 lb.', rarity: 'common', type: 'adventuring gear'},
	'chalk': {name: 'Chalk (1 piece)', cost: '1 cp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'chest': {name: 'Chest', cost: '5 gp', weight: '25 lb.', rarity: 'common', type: 'adventuring gear'},
	'climbers kit': {name: 'Climber\'s kit', cost: '25 gp', weight: '12 lb.', rarity: 'common', type: 'adventuring gear'},
	'clothes, common': {name: 'Clothes, common', cost: '5 sp', weight: '3 lb.', rarity: 'common', type: 'adventuring gear'},
	'clothes, costume': {name: 'Clothes, costume', cost: '5 gp', weight: '4 lb.', rarity: 'common', type: 'adventuring gear'},
	'clothes, fine': {name: 'Clothes, fine', cost: '15 gp', weight: '6 lb.', rarity: 'common', type: 'adventuring gear'},
	'clothes, travelers': {name: 'Clothes, traveler\'s', cost: '2 gp', weight: '4 lb.', rarity: 'common', type: 'adventuring gear'},
	'component pouch': {name: 'Component pouch', cost: '25 gp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'crowbar': {name: 'Crowbar', cost: '2 gp', weight: '5 lb.', rarity: 'common', type: 'adventuring gear'},
	'druidic focus, sprig of mistletoe': {name: 'Druidic Focus, Sprig of mistletoe', cost: '1 gp ', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'druidic focus, totem': {name: 'Druidic Focus, Totem', cost: '1 gp ', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'druidic focus, wooden staff': {name: 'Druidic Focus, Wooden staff', cost: '5 gp ', weight: '4 lb.', rarity: 'common', type: 'adventuring gear'},
	'druidic focus, yew wand': {name: 'Druidic Focus, Yew wand', cost: '10 gp ', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'fishing tackle': {name: 'Fishing tackle', cost: '1 gp', weight: '4 lb.', rarity: 'common', type: 'adventuring gear'},
	'flask or tankard': {name: 'Flask or tankard', cost: '2 cp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'grappling hook': {name: 'Grappling hook', cost: '2 gp', weight: '4 lb.', rarity: 'common', type: 'adventuring gear'},
	'hammer': {name: 'Hammer', cost: '1 gp', weight: '3 lb.', rarity: 'common', type: 'adventuring gear'},
	'hammer, sledge': {name: 'Hammer, sledge', cost: '2 gp', weight: '10 lb.', rarity: 'common', type: 'adventuring gear'},
	'healers kit': {name: 'Healer\'s kit', cost: '5 gp', weight: '3 lb.', rarity: 'common', type: 'adventuring gear'},
	'holy symbol, amulet': {name: 'Holy Symbol, Amulet', cost: '5 gp ', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'holy symbol, emblem': {name: 'Holy Symbol, Emblem', cost: '5 gp ', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'holy symbol, reliquary': {name: 'Holy Symbol, Reliquary', cost: '5 gp ', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'holy water': {name: 'Holy water (flask)', cost: '25 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'hourglass': {name: 'Hourglass', cost: '25 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'hunting trap': {name: 'Hunting trap', cost: '5 gp', weight: '25 lb.', rarity: 'common', type: 'adventuring gear'},
	'ink': {name: 'Ink (1 ounce bottle)', cost: '10 gp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'ink pen': {name: 'Ink pen', cost: '2 cp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'jug or pitcher': {name: 'Jug or pitcher', cost: '2 cp', weight: '4 lb.', rarity: 'common', type: 'adventuring gear'},
	'ladder': {name: 'Ladder (10 foot)', cost: '1 sp', weight: '25 lb.', rarity: 'common', type: 'adventuring gear'},
	'lamp': {name: 'Lamp', cost: '5 sp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'lantern, bullseye': {name: 'Lantern, bullseye', cost: '10 gp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'lantern, hooded': {name: 'Lantern, hooded', cost: '5 gp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'lock': {name: 'Lock', cost: '10 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'magnifying glass': {name: 'Magnifying glass', cost: '100 gp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'manacles': {name: 'Manacles', cost: '2 gp', weight: '6 lb.', rarity: 'common', type: 'adventuring gear'},
	'mess kit': {name: 'Mess kit', cost: '2 sp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'mirror, steel': {name: 'Mirror, steel', cost: '5 gp', weight: '1/2 lb.', rarity: 'common', type: 'adventuring gear'},
	'oil': {name: 'Oil (flask)', cost: '1 sp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'paper': {name: 'Paper (one sheet)', cost: '2 sp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'parchment': {name: 'Parchment (one sheet)', cost: '1 sp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'perfume': {name: 'Perfume (vial)', cost: '5 gp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'pick, miners': {name: 'Pick, miner\'s', cost: '2 gp', weight: '10 lb.', rarity: 'common', type: 'adventuring gear'},
	'piton': {name: 'Piton', cost: '5 cp', weight: '1/4 lb.', rarity: 'common', type: 'adventuring gear'},
	'poison, basic': {name: 'Poison, basic (vial)', cost: '100 gp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'pole': {name: 'Pole (10-foot)', cost: '5 cp', weight: '7 lb.', rarity: 'common', type: 'adventuring gear'},
	'pot, iron': {name: 'Pot, iron', cost: '2 gp', weight: '10 lb.', rarity: 'common', type: 'adventuring gear'},
	'potion of healing': {name: 'Potion of healing', cost: '50 gp', weight: '1/2 lb.', rarity: 'common', type: 'adventuring gear'},
	'pouch': {name: 'Pouch', cost: '5 sp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'quiver': {name: 'Quiver', cost: '1 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'ram, portable': {name: 'Ram, portable', cost: '4 gp', weight: '35 lb.', rarity: 'common', type: 'adventuring gear'},
	'rations': {name: 'Rations (1 day)', cost: '5 sp', weight: '2 lb.', rarity: 'common', type: 'adventuring gear'},
	'robes': {name: 'Robes', cost: '1 gp', weight: '4 lb.', rarity: 'common', type: 'adventuring gear'},
	'rope, hempen': {name: 'Rope, hempen (50 feet)', cost: '1 gp', weight: '10 lb.', rarity: 'common', type: 'adventuring gear'},
	'rope, silk': {name: 'Rope, silk (50 feet)', cost: '10 gp', weight: '5 lb.', rarity: 'common', type: 'adventuring gear'},
	'sack': {name: 'Sack', cost: '1 cp', weight: '1/2 lb.', rarity: 'common', type: 'adventuring gear'},
	'scale, merchants': {name: 'Scale, merchant\'s', cost: '5 gp', weight: '3 lb.', rarity: 'common', type: 'adventuring gear'},
	'sealing wax': {name: 'Sealing wax', cost: '5 sp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'shovel': {name: 'Shovel', cost: '2 gp', weight: '5 lb.', rarity: 'common', type: 'adventuring gear'},
	'signal whistle': {name: 'Signal whistle', cost: '5 cp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'signet ring': {name: 'Signet ring', cost: '5 gp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'soap': {name: 'Soap', cost: '2 cp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'spellbook': {name: 'Spellbook', cost: '50 gp', weight: '3 lb.', rarity: 'common', type: 'adventuring gear'},
	'spikes, iron': {name: 'Spikes, iron (10)', cost: '1 gp', weight: '5 lb.', rarity: 'common', type: 'adventuring gear'},
	'spyglass': {name: 'Spyglass', cost: '1,000 gp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'tent, two-person': {name: 'Tent, two-person', cost: '2 gp', weight: '20 lb.', rarity: 'common', type: 'adventuring gear'},
	'tinderbox': {name: 'Tinderbox', cost: '5 sp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'torch': {name: 'Torch', cost: '1 cp', weight: '1 lb.', rarity: 'common', type: 'adventuring gear'},
	'vial': {name: 'Vial', cost: '1 gp', weight: '-', rarity: 'common', type: 'adventuring gear'},
	'waterskin': {name: 'Waterskin', cost: '2 sp', weight: '5 lb. (full)', rarity: 'common', type: 'adventuring gear'},
	'whetstone': {name: 'Whetstone', cost: '1 cp', weight: 'l lb.', rarity: 'common', type: 'adventuring gear'},
	
	'alchemists supplies': {name: "Alchemist's supplies", cost: '50 gp', weight: '8 lb.', rarity: 'common', type: 'artisans tools'},
	'brewers supplies': {name: "Brewer's supplies", cost: '20 gp', weight: '9 lb.', rarity: 'common', type: 'artisans tools'},
	'calligraphers supplies': {name: "Calligrapher's supplies", cost: '10 gp', weight: '5 lb.', rarity: 'common', type: 'artisans tools'},
	'carpenters tools': {name: "Carpenter's tools", cost: '8 gp', weight: '6 lb.', rarity: 'common', type: 'artisans tools'},
	'cartographers tools': {name: "Cartographer's tools", cost: '15 gp', weight: '6 lb.', rarity: 'common', type: 'artisans tools'},
	'cobblers tools': {name: "Cobbler's tools", cost: '5 gp', weight: '5 lb.', rarity: 'common', type: 'artisans tools'},
	'cooks utensils': {name: "Cook's utensils", cost: '1 gp', weight: '8 lb.', rarity: 'common', type: 'artisans tools'},
	'glassblowers tools': {name: "Glassblower's tools", cost: '30 gp', weight: '5 lb.', rarity: 'common', type: 'artisans tools'},
	'jewelers tools': {name: "Jeweler's tools", cost: '25 gp', weight: '2 lb.', rarity: 'common', type: 'artisans tools'},
	'leatherworkers tools': {name: "Leatherworker's tools", cost: '5 gp', weight: '5 lb.', rarity: 'common', type: 'artisans tools'},
	'masons tools': {name: "Mason's tools", cost: '10 gp', weight: '8 lb.', rarity: 'common', type: 'artisans tools'},
	'painters supplies': {name: "Painter's supplies", cost: '10 gp', weight: '5 lb.', rarity: 'common', type: 'artisans tools'},
	'potters tools': {name: "Potter's tools", cost: '10 gp', weight: '3 lb.', rarity: 'common', type: 'artisans tools'},
	'smiths tools': {name: "Smith's tools", cost: '20 gp', weight: '8 lb.', rarity: 'common', type: 'artisans tools'},
	'tinkers tools': {name: "Tinker's tools", cost: '50 gp', weight: '10 lb.', rarity: 'common', type: 'artisans tools'},
	'weavers tools': {name: "Weaver's tools", cost: '1 gp', weight: '5 lb.', rarity: 'common', type: 'artisans tools'},
	'woodcarvers tools': {name: "Woodcarver's tools", cost: '1 gp', weight: '5 lb.', rarity: 'common', type: 'artisans tools'},

	'disguise kit': {name: "Disguise kit", cost: '25 gp', weight: '3 lb.', rarity: 'common', type: 'other tools'},
	'forgery kit': {name: "Forgery kit", cost: '15 gp', weight: '5 lb.', rarity: 'common', type: 'other tools'},
	'herbalism kit': {name: "Herbalism kit", cost: '5 gp', weight: '3 lb.', rarity: 'common', type: 'other tools'},
	'navigators tools': {name: "Navigator's tools", cost: '25 gp', weight: '2 lb.', rarity: 'common', type: 'other tools'},
	'poisoners kit': {name: "Poisoner's kit", cost: '50 gp', weight: '2 lb.', rarity: 'common', type: 'other tools'},
	'thieves tools': {name: "Thieves' tools", cost: '25 gp', weight: '1 lb.', rarity: 'common', type: 'other tools'},

	'bagpipes': {name: "Bagpipes", cost: '30 gp', weight: '6 lb.', rarity: 'common', type: 'musical instruments'},
	'drum': {name: "Drum", cost: '6 gp', weight: '3 lb.', rarity: 'common', type: 'musical instruments'},
	'dulcimer': {name: "Dulcimer", cost: '25 gp', weight: '10 lb.', rarity: 'common', type: 'musical instruments'},
	'flute': {name: "Flute", cost: '2 gp', weight: '1 lb.', rarity: 'common', type: 'musical instruments'},
	'lute': {name: "Lute", cost: '35 gp', weight: '2 lb.', rarity: 'common', type: 'musical instruments'},
	'lyre': {name: "Lyre", cost: '30 gp', weight: '2 lb.', rarity: 'common', type: 'musical instruments'},
	'horn': {name: "Horn", cost: '3 gp', weight: '2 lb.', rarity: 'common', type: 'musical instruments'},
	'pan flute': {name: "Pan flute", cost: '12 gp', weight: '2 lb.', rarity: 'common', type: 'musical instruments'},
	'shawm': {name: "Shawm", cost: '2 gp', weight: '1 lb.', rarity: 'common', type: 'musical instruments'},
	'viol': {name: "Viol", cost: '30 gp', weight: '1 lb.', rarity: 'common', type: 'musical instruments'},

	'dice set': {name: "Dice set", cost: '1 sp', weight: '-', rarity: 'common', type: 'gaming sets'},
	'dragonchess set': {name: "Dragonchess set", cost: '1 gp', weight: '1/2 lb.', rarity: 'common', type: 'gaming sets'},
	'playing card set': {name: "Playing card set", cost: '5 sp', weight: '-', rarity: 'common', type: 'gaming sets'},
	'three-dragon ante set': {name: "Three-Dragon Ante set", cost: '1 gp', weight: '-', rarity: 'common', type: 'gaming sets'},

// 	'barding': {name: "Barding", cost: 'x4', weight: 'x2', rarity: 'common', type: 'tack'},
	'bit and bridle': {name: "Bit and bridle", cost: '2 gp', weight: '1 lb.', rarity: 'common', type: 'tack'},
	'carriage': {name: "Carriage", cost: '100 gp', weight: '600 lb.', rarity: 'common', type: 'tack'},
	'cart': {name: "Cart", cost: '15 gp', weight: '200 lb.', rarity: 'common', type: 'tack'},
	'chariot': {name: "Chariot", cost: '250 gp', weight: '100 lb.', rarity: 'common', type: 'tack'},
	'feed (per day)': {name: "Feed (per day)", cost: '5 cp', weight: '10 lb.', rarity: 'common', type: 'tack'},
	'saddlebags': {name: "Saddlebags", cost: '4 gp', weight: '8 lb.', rarity: 'common', type: 'tack'},
	'sled': {name: "Sled", cost: '20 gp', weight: '300 lb.', rarity: 'common', type: 'tack'},
	'stabling (per day)': {name: "Stabling (per day)", cost: '5 sp', weight: '-', rarity: 'common', type: 'tack'},
	'wagon': {name: "Wagon", cost: '35 gp', weight: '400 lb.', rarity: 'common', type: 'tack'},

	'saddle, exotic': {name: "Saddle, Exotic", cost: '60 gp', weight: '40 lb.', rarity: 'common', type: 'tack'},
	'saddle, military': {name: "Saddle, Military", cost: '20 gp', weight: '30 lb.', rarity: 'common', type: 'tack'},
	'saddle, pack': {name: "Saddle, Pack", cost: '5 gp', weight: '15 lb.', rarity: 'common', type: 'tack'},
	'saddle, riding': {name: "Saddle, Riding", cost: '10 gp', weight: '25 lb.', rarity: 'common', type: 'tack'},

	// vessels
	'galley': {name: "Galley", cost: '30,000 gp', speed: '4 mph', weight: 'too much', rarity: 'common', type: 'vessel'},
	'keelboat': {name: "Keelboat", cost: '3,000 gp', speed: '1 mph', weight: 'too much', rarity: 'common', type: 'vessel'},
	'longship': {name: "Longship", cost: '10,000 gp', speed: '3 mph', weight: 'too much', rarity: 'common', type: 'vessel'},
	'rowboat': {name: "Rowboat", cost: '50 gp', speed: '1 1/2 mph', weight: '100 lb.', rarity: 'common', type: 'vessel'},
	'sailing ship': {name: "Sailing ship", cost: '10,000 gp', speed: '2 mph', weight: 'too much', rarity: 'common', type: 'vessel'},
	'warship': {name: "Warship", cost: '25,000 gp', speed: '2 1/2 mph', weight: 'too much', rarity: 'common', type: 'vessel'},
	
	'camel': {name: "Camel", cost: '50 gp', speed: '50 ft.', carry_capacity: '480 lb.', rarity: 'common', type: 'mount'},
	'donkey': {name: "Donkey", cost: '8 gp', speed: '40 ft.', carry_capacity: '420 lb.', rarity: 'common', type: 'mount'},
	'mule': {name: "Mule", cost: '8 gp', speed: '40 ft.', carry_capacity: '420 lb.', rarity: 'common', type: 'mount'},
	'elephant': {name: "Elephant", cost: '200 gp', speed: '40 ft.', carry_capacity: '1,320 lb.', rarity: 'common', type: 'mount'},
	'draft horse': {name: "Draft horse", cost: '50 gp', speed: '40 ft.', carry_capacity: '540 lb.', rarity: 'common', type: 'mount'},
	'riding horse': {name: "Riding horse", cost: '75 gp', speed: '60 ft.', carry_capacity: '480 lb.', rarity: 'common', type: 'mount'},
	'mastiff': {name: "Mastiff", cost: '25 gp', speed: '40 ft.', carry_capacity: '195 lb.', rarity: 'common', type: 'mount'},
	'pony': {name: "Pony", cost: '30 gp', speed: '40 ft.', carry_capacity: '225 lb.', rarity: 'common', type: 'mount'},
	'warhorse': {name: "Warhorse", cost: '400 gp', speed: '60 ft.', carry_capacity: '540 lb.', rarity: 'common', type: 'mount'},

	// weapons
	'club': {name: "Club", cost: '1 sp', damage: '1d4 bludgeoning', weight: '2 lb.', properties: 'Light', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'dagger': {name: "Dagger", cost: '2 gp', damage: '1d4 piercing', weight: '1 lb.', properties: 'Finesse, light, thrown (range 20/60)', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'greatclub': {name: "Greatclub", cost: '2 sp', damage: '1d8 bludgeoning', weight: '10 lb.', properties: 'Two-handed', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'handaxe': {name: "Handaxe", cost: '5 gp', damage: '1d6 slashing', weight: '2 lb.', properties: 'Light, thrown (range 20/60)', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'javelin': {name: "Javelin", cost: '5 sp', damage: '1d6 piercing', weight: '2 lb.', properties: 'Thrown (range 30/120)', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'light hammer': {name: "Light hammer", cost: '2 gp', damage: '1d4 bludgeoning', weight: '2 lb.', properties: 'Light, thrown (range 20/60)', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'mace': {name: "Mace", cost: '5 gp', damage: '1d6 bludgeoning', weight: '4 lb.', properties: '-', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'quarterstaff': {name: "Quarterstaff", cost: '2 sp', damage: '1d6 bludgeoning', weight: '4 lb.', properties: 'Versatile (1d8)', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'sickle': {name: "Sickle", cost: '1 gp', damage: '1d4 slashing', weight: '2 lb.', properties: 'Light', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},
	'spear': {name: "Spear", cost: '1 gp', damage: '1d6 piercing', weight: '3 lb.', properties: 'Thrown (range 20/60), versatile (1d8)', type: 'weapon', subtype: 'simple', ranged: false, rarity: 'common'},

	'crossbow, light': {name: "Crossbow, light", cost: '25 gp', damage: '1d8 piercing', weight: '5 lb.', properties: 'Ammunition (range 80/320), loading, two-handed', type: 'weapon', subtype: 'simple', ranged: true, rarity: 'common'},
	'dart': {name: "Dart", cost: '5 cp', damage: '1d4 piercing', weight: '1/4 lb.', properties: 'Finesse, thrown (range 20/60)', type: 'weapon', subtype: 'simple', ranged: true, rarity: 'common'},
	'shortbow': {name: "Shortbow", cost: '25 gp', damage: '1d6 piercing', weight: '2 lb.', properties: 'Ammunition (range 80/320), two-handed', type: 'weapon', subtype: 'simple', ranged: true, rarity: 'common'},
	'sling': {name: "Sling", cost: '1 sp', damage: '1d4 bludgeoning', weight: '-', properties: 'Ammunition (range 30/120)', type: 'weapon', subtype: 'simple', ranged: true, rarity: 'common'},

	'battleaxe': {name: "Battleaxe", cost: '10 gp', damage: '1d8 slashing', weight: '4 lb.', properties: 'Versatile (1d10)', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'flail': {name: "Flail", cost: '10 gp', damage: '1d8 bludgeoning', weight: '2 lb.', properties: '-', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'glaive': {name: "Glaive", cost: '20 gp', damage: '1d10 slashing', weight: '6 lb.', properties: 'Heavy, reach, two-handed', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'greataxe': {name: "Greataxe", cost: '30 gp', damage: '1d12 slashing', weight: '7 lb.', properties: 'Heavy, two-handed', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'greatsword': {name: "Greatsword", cost: '50 gp', damage: '2d6 slashing', weight: '6 lb.', properties: 'Heavy, two-handed', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'halberd': {name: "Halberd", cost: '20 gp', damage: '1d10 slashing', weight: '6 lb.', properties: 'Heavy, reach, two-handed', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'lance': {name: "Lance", cost: '10 gp', damage: '1d12 piercing', weight: '6 lb.', properties: 'Reach, special', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'longsword': {name: "Longsword", cost: '15 gp', damage: '1d8 slashing', weight: '3 lb.', properties: 'Versatile (1d10)', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'maul': {name: "Maul", cost: '10 gp', damage: '2d6 bludgeoning', weight: '10 lb.', properties: 'Heavy, two-handed', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'morningstar': {name: "Morningstar", cost: '15 gp', damage: '1d8 piercing', weight: '4 lb.', properties: '-', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'pike': {name: "Pike", cost: '5 gp', damage: '1d10 piercing', weight: '18 lb.', properties: 'Heavy, reach, two-handed', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'rapier': {name: "Rapier", cost: '25 gp', damage: '1d8 piercing', weight: '2 lb.', properties: 'Finesse', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'scimitar': {name: "Scimitar", cost: '25 gp', damage: '1d6 slashing', weight: '3 lb.', properties: 'Finesse, light', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'shortsword': {name: "Shortsword", cost: '10 gp', damage: '1d6 piercing', weight: '2 lb.', properties: 'Finesse, light', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'trident': {name: "Trident", cost: '5 gp', damage: '1d6 piercing', weight: '4 lb.', properties: 'Thrown (range 20/60), versatile (1d8)', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'war pick': {name: "War pick", cost: '5 gp', damage: '1d8 piercing', weight: '2 lb.', properties: '-', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'warhammer': {name: "Warhammer", cost: '15 gp', damage: '1d8 bludgeoning', weight: '2 lb.', properties: 'Versatile (1d10)', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},
	'whip': {name: "Whip", cost: '2 gp', damage: '1d4 slashing', weight: '3 lb.', properties: 'Finesse, reach', type: 'weapon', subtype: 'martial', ranged: false, rarity: 'common'},

	'blowgun': {name: "Blowgun", cost: '10 gp', damage: '1 piercing', weight: '1 lb.', properties: 'Ammunition (range 25/100), loading', type: 'weapon', subtype: 'martial', ranged: true, rarity: 'common'},
	'crossbow, hand': {name: "Crossbow, hand", cost: '75 gp', damage: '1d6 piercing', weight: '3 lb.', properties: 'Ammunition (range 30/120), light, loading', type: 'weapon', subtype: 'martial', ranged: true, rarity: 'common'},
	'crossbow, heavy': {name: "Crossbow, heavy", cost: '50 gp', damage: '1d10 piercing', weight: '18 lb.', properties: 'Ammunition (range 100/400), heavy, loading, two-handed', type: 'weapon', subtype: 'martial', ranged: true, rarity: 'common'},
	'longbow': {name: "Longbow", cost: '50 gp', damage: '1d8 piercing', weight: '2 lb.', properties: 'Ammunition (range 150/600), heavy, two-handed', type: 'weapon', subtype: 'martial', ranged: true, rarity: 'common'},
	'net': {name: "Net", cost: '1 gp', damage: '-', weight: '3 lb.', properties: 'Special, thrown (range 5/15)', type: 'weapon', subtype: 'martial', ranged: true, rarity: 'common'},
	
	// armor
	'padded': {name: "Padded", cost: '5 gp', ac: '11 + Dex modifier', min_str: '-', stealth: 'Disadvantage', weight: '8 lb.', type: 'armor', subtype: 'light', metal: false, rarity: 'common'},
	'leather': {name: "Leather", cost: '10 gp', ac: '11 + Dex modifier', min_str: '-', stealth: '-', weight: '10 lb.', type: 'armor', subtype: 'light', metal: false, rarity: 'common'},
	'studded leather': {name: "Studded leather", cost: '45 gp', ac: '12 + Dex modifier', min_str: '-', stealth: '-', weight: '13 lb.', type: 'armor', subtype: 'light', metal: false, rarity: 'common'},

	'hide': {name: "Hide", cost: '10 gp', ac: '12 + Dex modifier (max 2)', min_str: '-', stealth: '-', weight: '12 lb.', type: 'armor', subtype: 'medium', metal: false, rarity: 'common'},
	'chain shirt': {name: "Chain shirt", cost: '50 gp', ac: '13 + Dex modifier (max 2)', min_str: '-', stealth: '-', weight: '20 lb.', type: 'armor', subtype: 'medium', metal: true, rarity: 'common'},
	'scale mail': {name: "Scale mail", cost: '50 gp', ac: '14 + Dex modifier (max 2)', min_str: '-', stealth: 'Disadvantage', weight: '45 lb.', type: 'armor', subtype: 'medium', metal: true, rarity: 'common'},
	'breastplate': {name: "Breastplate", cost: '400 gp', ac: '14 + Dex modifier (max 2)', min_str: '-', stealth: '-', weight: '20 lb.', type: 'armor', subtype: 'medium', metal: true, rarity: 'common'},
	'half plate': {name: "Half plate", cost: '750 gp', ac: '15 + Dex modifier (max 2)', min_str: '-', stealth: 'Disadvantage', weight: '40 lb.', type: 'armor', subtype: 'medium', metal: true, rarity: 'common'},

	'ring mail': {name: "Ring mail", cost: '30 gp', ac: '14', min_str: '-', stealth: 'Disadvantage', weight: '40 lb.', type: 'armor', subtype: 'heavy', metal: true, rarity: 'common'},
	'chain mail': {name: "Chain mail", cost: '75 gp', ac: '16', min_str: 'Str 13', stealth: 'Disadvantage', weight: '55 lb.', type: 'armor', subtype: 'heavy', metal: true, rarity: 'common'},
	'splint': {name: "Splint", cost: '200 gp', ac: '17', min_str: 'Str 15', stealth: 'Disadvantage', weight: '60 lb.', type: 'armor', subtype: 'heavy', metal: true, rarity: 'common'},
	'plate': {name: "Plate", cost: '1,500 gp', ac: '18', min_str: 'Str 15', stealth: 'Disadvantage', weight: '65 lb.', type: 'armor', subtype: 'heavy', metal: true, rarity: 'common'},

	'shield': {name: "Shield", cost: '10 gp', ac: '+2', min_str: '-', stealth: '-', weight: '6 lb.', type: 'armor', subtype: 'shield', metal: false, rarity: 'common'},

	// magic items
	'amulet of health': {"name":"Amulet of Health","id":"amulet of health","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'amulet of proof against detection and location': {"name":"Amulet of Proof against Detection and Location","id":"amulet of proof against detection and location","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'amulet of the planes': {"name":"Amulet of the Planes","id":"amulet of the planes","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'apparatus of the crab': {"name":"Apparatus of the Crab","id":"apparatus of the crab","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"legendary"},
	'bag of beans': {"name":"Bag of Beans","id":"bag of beans","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'bag of devouring': {"name":"Bag of Devouring","id":"bag of devouring","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'bag of holding': {"name":"Bag of Holding","id":"bag of holding","pocket_dimension": true, "magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'bag of tricks': {"name":"Bag of Tricks","id":"bag of tricks","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'bead of force': {"name":"Bead of Force","id":"bead of force","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'belt of dwarvenkind': {"name":"Belt of Dwarvenkind","id":"belt of dwarvenkind","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'belt of hill giant strength': {"name":"Belt of Hill Giant Strength","id":"belt of hill giant strength","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'belt of stone giant strength': {"name":"Belt of Stone Giant Strength","id":"belt of stone giant strength","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'belt of frost giant strength': {"name":"Belt of Frost Giant Strength","id":"belt of frost giant strength","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'belt of fire giant strength': {"name":"Belt of Fire Giant Strength","id":"belt of fire giant strength","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'belt of cloud giant strength': {"name":"Belt of Cloud Giant Strength","id":"belt of cloud giant strength","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"legendary"},
	'belt of storm giant strength': {"name":"Belt of Storm Giant Strength","id":"belt of storm giant strength","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"legendary"},
	'boots of elvenkind': {"name":"Boots of Elvenkind","id":"boots of elvenkind","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'boots of levitation': {"name":"Boots of Levitation","id":"boots of levitation","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'boots of speed': {"name":"Boots of Speed","id":"boots of speed","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'boots of striding and springing': {"name":"Boots of Striding and Springing","id":"boots of striding and springing","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'boots of the winterlands': {"name":"Boots of the Winterlands","id":"boots of the winterlands","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'bowl of commanding water elementals': {"name":"Bowl of Commanding Water Elementals","id":"bowl of commanding water elementals","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'bracers of archery': {"name":"Bracers of Archery","id":"bracers of archery","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'bracers of defense': {"name":"Bracers of Defense","id":"bracers of defense","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'brazier of commanding fire elementals': {"name":"Brazier of Commanding Fire Elementals","id":"brazier of commanding fire elementals","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'brooch of shielding': {"name":"Brooch of Shielding","id":"brooch of shielding","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'broom of flying': {"name":"Broom of Flying","id":"broom of flying","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'candle of invocation': {"name":"Candle of Invocation","id":"candle of invocation","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'cape of the mountebank': {"name":"Cape of the Mountebank","id":"cape of the mountebank","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'carpet of flying': {"name":"Carpet of Flying","id":"carpet of flying","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'censer of controlling air elementals': {"name":"Censer of Controlling Air Elementals","id":"censer of controlling air elementals","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'chime of opening': {"name":"Chime of Opening","id":"chime of opening","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'circlet of blasting': {"name":"Circlet of Blasting","id":"circlet of blasting","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'cloak of arachnida': {"name":"Cloak of Arachnida","id":"cloak of arachnida","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'cloak of displacement': {"name":"Cloak of Displacement","id":"cloak of displacement","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'cloak of elvenkind': {"name":"Cloak of Elvenkind","id":"cloak of elvenkind","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'cloak of protection': {"name":"Cloak of Protection","id":"cloak of protection","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'cloak of the bat': {"name":"Cloak of the Bat","id":"cloak of the bat","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'cloak of the manta ray': {"name":"Cloak of the Manta Ray","id":"cloak of the manta ray","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'crystal ball': {"name":"Crystal Ball","id":"crystal ball","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'crystal ball of mind reading': {"name":"Crystal Ball of Mind Reading","id":"crystal ball of mind reading","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"legendary"},
	'crystal ball of telepathy': {"name":"Crystal Ball of Telepathy","id":"crystal ball of telepathy","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"legendary"},
	'crystal ball of true seeing': {"name":"Crystal Ball of True Seeing","id":"crystal ball of true seeing","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"legendary"},
	'cube of force': {"name":"Cube of Force","id":"cube of force","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'cubic gate': {"name":"Cubic Gate","id":"cubic gate","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"legendary"},
	'decanter of endless water': {"name":"Decanter of Endless Water","id":"decanter of endless water","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'deck of illusions': {"name":"Deck of Illusions","id":"deck of illusions","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'deck of many things': {"name":"Deck of Many Things","id":"deck of many things","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"legendary"},
	'dimensional shackles': {"name":"Dimensional Shackles","id":"dimensional shackles","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'dust of disappearance': {"name":"Dust of Disappearance","id":"dust of disappearance","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'dust of dryness': {"name":"Dust of Dryness","id":"dust of dryness","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'dust of sneezing and choking': {"name":"Dust of Sneezing and Choking","id":"dust of sneezing and choking","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'efficient quiver': {"name":"Efficient Quiver","id":"efficient quiver","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'efreeti bottle': {"name":"Efreeti Bottle","id":"efreeti bottle","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'elemental gem': {"name":"Elemental Gem","id":"elemental gem","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'eversmoking bottle': {"name":"Eversmoking Bottle","id":"eversmoking bottle","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'eyes of charming': {"name":"Eyes of Charming","id":"eyes of charming","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'eyes of minute seeing': {"name":"Eyes of Minute Seeing","id":"eyes of minute seeing","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'eyes of the eagle': {"name":"Eyes of the Eagle","id":"eyes of the eagle","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'feather token': {"name":"Feather Token","id":"feather token","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'folding boat': {"name":"Folding Boat","id":"folding boat","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'gauntlets of ogre power': {"name":"Gauntlets of Ogre Power","id":"gauntlets of ogre power","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'gem of brightness': {"name":"Gem of Brightness","id":"gem of brightness","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'gem of seeing': {"name":"Gem of Seeing","id":"gem of seeing","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'gloves of missile snaring': {"name":"Gloves of Missile Snaring","id":"gloves of missile snaring","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'gloves of swimming and climbing': {"name":"Gloves of Swimming and Climbing","id":"gloves of swimming and climbing","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'goggles of night': {"name":"Goggles of Night","id":"goggles of night","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'handy haversack': {"name":"Handy Haversack","id":"handy haversack","pocket_dimension": true, "magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'hat of disguise': {"name":"Hat of Disguise","id":"hat of disguise","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'headband of intellect': {"name":"Headband of Intellect","id":"headband of intellect","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'helm of brilliance': {"name":"Helm of Brilliance","id":"helm of brilliance","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'helm of comprehending languages': {"name":"Helm of Comprehending Languages","id":"helm of comprehending languages","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'helm of telepathy': {"name":"Helm of Telepathy","id":"helm of telepathy","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'helm of teleportation': {"name":"Helm of Teleportation","id":"helm of teleportation","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'horn of blasting': {"name":"Horn of Blasting","id":"horn of blasting","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'horseshoes of a zephyr': {"name":"Horseshoes of a Zephyr","id":"horseshoes of a zephyr","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'horseshoes of speed': {"name":"Horseshoes of Speed","id":"horseshoes of speed","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'immovable rod': {"name":"Immovable Rod","id":"immovable rod","magic_item":true,"requires_attunement":false,"type":"Rod","rarity":"uncommon"},
	'instant fortress': {"name":"Instant Fortress","id":"instant fortress","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'iron bands of binding': {"name":"Iron Bands of Binding","id":"iron bands of binding","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'iron flask': {"name":"Iron Flask","id":"iron flask","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"legendary"},
	'lantern of revealing': {"name":"Lantern of Revealing","id":"lantern of revealing","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'mantle of spell resistance': {"name":"Mantle of Spell Resistance","id":"mantle of spell resistance","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'manual of bodily health': {"name":"Manual of Bodily Health","id":"manual of bodily health","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'manual of gainful exercise': {"name":"Manual of Gainful Exercise","id":"manual of gainful exercise","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'manual of golems': {"name":"Manual of Golems","id":"manual of golems","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'manual of quickness of action': {"name":"Manual of Quickness of Action","id":"manual of quickness of action","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'marvelous pigments': {"name":"Marvelous Pigments","id":"marvelous pigments","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'medallion of thoughts': {"name":"Medallion of Thoughts","id":"medallion of thoughts","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'mirror of life trapping': {"name":"Mirror of Life Trapping","id":"mirror of life trapping","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'necklace of adaptation': {"name":"Necklace of Adaptation","id":"necklace of adaptation","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'necklace of fireballs': {"name":"Necklace of Fireballs","id":"necklace of fireballs","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'necklace of prayer beads': {"name":"Necklace of Prayer Beads","id":"necklace of prayer beads","magic_item":true,"requires_attunement":"cleric, druid, or paladin","type":"Wondrous item","rarity":"rare"},
	'oil of etherealness': {"name":"Oil of Etherealness","id":"oil of etherealness","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'oil of sharpness': {"name":"Oil of Sharpness","id":"oil of sharpness","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"very rare"},
	'oil of slipperiness': {"name":"Oil of Slipperiness","id":"oil of slipperiness","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'pearl of power': {"name":"Pearl of Power","id":"pearl of power","magic_item":true,"requires_attunement":"spellcaster","type":"Wondrous item","rarity":"uncommon"},
	'periapt of health': {"name":"Periapt of Health","id":"periapt of health","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'periapt of proof against poison': {"name":"Periapt of Proof against Poison","id":"periapt of proof against poison","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'periapt of wound closure': {"name":"Periapt of Wound Closure","id":"periapt of wound closure","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'philter of love': {"name":"Philter of Love","id":"philter of love","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'pipes of haunting': {"name":"Pipes of Haunting","id":"pipes of haunting","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'pipes of the sewers': {"name":"Pipes of the Sewers","id":"pipes of the sewers","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'portable hole': {"name":"Portable Hole","id":"portable hole", "pocket_dimension": true, "magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'potion of animal friendship': {"name":"Potion of Animal Friendship","id":"potion of animal friendship","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'potion of clairvoyance': {"name":"Potion of Clairvoyance","id":"potion of clairvoyance","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of climbing': {"name":"Potion of Climbing","id":"potion of climbing","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"common"},
	'potion of diminution': {"name":"Potion of Diminution","id":"potion of diminution","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of flying': {"name":"Potion of Flying","id":"potion of flying","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"very rare"},
	'potion of gaseous form': {"name":"Potion of Gaseous Form","id":"potion of gaseous form","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of hill giant strength': {"name":"Potion of Hill Giant Strength","id":"potion of hill giant strength","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'potion of frost giant strength': {"name":"Potion of Frost Giant Strength","id":"potion of frost giant strength","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of stone giant strength': {"name":"Potion of Stone Giant Strength","id":"potion of stone giant strength","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of fire giant strength': {"name":"Potion of Fire Giant Strength","id":"potion of fire giant strength","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of cloud giant strength': {"name":"Potion of Cloud Giant Strength","id":"potion of cloud giant strength","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"very rare"},
	'potion of storm giant strength': {"name":"Potion of Storm Giant Strength","id":"potion of storm giant strength","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"legendary"},
	'potion of growth': {"name":"Potion of Growth","id":"potion of growth","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'potion of healing': {"name":"Potion of Healing","id":"potion of healing","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"common"},
	'potion of greater healing': {"name":"Potion of Greater Healing","id":"potion of greater healing","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'potion of superior healing': {"name":"Potion of Superior Healing","id":"potion of superior healing","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of supreme healing': {"name":"Potion of Supreme Healing","id":"potion of supreme healing","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"very rare"},
	'potion of heroism': {"name":"Potion of Heroism","id":"potion of heroism","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of invisibility': {"name":"Potion of Invisibility","id":"potion of invisibility","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"very rare"},
	'potion of mind reading': {"name":"Potion of Mind Reading","id":"potion of mind reading","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"rare"},
	'potion of poison': {"name":"Potion of Poison","id":"potion of poison","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'potion of resistance': {"name":"Potion of Resistance","id":"potion of resistance","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'potion of speed': {"name":"Potion of Speed","id":"potion of speed","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"very rare"},
	'potion of water breathing': {"name":"Potion of Water Breathing","id":"potion of water breathing","magic_item":true,"requires_attunement":false,"type":"Potion","rarity":"uncommon"},
	'restorative ointment': {"name":"Restorative Ointment","id":"restorative ointment","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'ring of animal influence': {"name":"Ring of Animal Influence","id":"ring of animal influence","magic_item":true,"requires_attunement":false,"type":"Ring","rarity":"rare"},
	'ring of djinni summoning': {"name":"Ring of Djinni Summoning","id":"ring of djinni summoning","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"legendary"},
	'ring of elemental command': {"name":"Ring of Elemental Command","id":"ring of elemental command","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"legendary"},
	'ring of evasion': {"name":"Ring of Evasion","id":"ring of evasion","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"rare"},
	'ring of feather falling': {"name":"Ring of Feather Falling","id":"ring of feather falling","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"rare"},
	'ring of free action': {"name":"Ring of Free Action","id":"ring of free action","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"rare"},
	'ring of invisibility': {"name":"Ring of Invisibility","id":"ring of invisibility","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"legendary"},
	'ring of jumping': {"name":"Ring of Jumping","id":"ring of jumping","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"uncommon"},
	'ring of mind shielding': {"name":"Ring of Mind Shielding","id":"ring of mind shielding","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"uncommon"},
	'ring of protection': {"name":"Ring of Protection","id":"ring of protection","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"rare"},
	'ring of regeneration': {"name":"Ring of Regeneration","id":"ring of regeneration","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"very rare"},
	'ring of resistance': {"name":"Ring of Resistance","id":"ring of resistance","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"rare"},
	'ring of spell storing': {"name":"Ring of Spell Storing","id":"ring of spell storing","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"rare"},
	'ring of spell turning': {"name":"Ring of Spell Turning","id":"ring of spell turning","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"legendary"},
	'ring of swimming': {"name":"Ring of Swimming","id":"ring of swimming","magic_item":true,"requires_attunement":false,"type":"Ring","rarity":"uncommon"},
	'ring of telekinesis': {"name":"Ring of Telekinesis","id":"ring of telekinesis","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"very rare"},
	'ring of the ram': {"name":"Ring of the Ram","id":"ring of the ram","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"rare"},
	'ring of three wishes': {"name":"Ring of Three Wishes","id":"ring of three wishes","magic_item":true,"requires_attunement":false,"type":"Ring","rarity":"legendary"},
	'ring of warmth': {"name":"Ring of Warmth","id":"ring of warmth","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"uncommon"},
	'ring of water walking': {"name":"Ring of Water Walking","id":"ring of water walking","magic_item":true,"requires_attunement":false,"type":"Ring","rarity":"uncommon"},
	'ring of x-ray vision': {"name":"Ring of X-ray Vision","id":"ring of x-ray vision","magic_item":true,"requires_attunement":true,"type":"Ring","rarity":"rare"},
	'robe of eyes': {"name":"Robe of Eyes","id":"robe of eyes","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	'robe of scintillating colors': {"name":"Robe of Scintillating Colors","id":"robe of scintillating colors","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'robe of stars': {"name":"Robe of Stars","id":"robe of stars","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"very rare"},
	'robe of the archmagi': {"name":"Robe of the Archmagi","id":"robe of the archmagi","magic_item":true,"requires_attunement":"sorcerer, warlock, or wizard","type":"Wondrous item","rarity":"legendary"},
	'robe of useful items': {"name":"Robe of Useful Items","id":"robe of useful items","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'rod of absorption': {"name":"Rod of Absorption","id":"rod of absorption","magic_item":true,"requires_attunement":true,"type":"Rod","rarity":"very rare"},
	'rod of alertness': {"name":"Rod of Alertness","id":"rod of alertness","magic_item":true,"requires_attunement":true,"type":"Rod","rarity":"very rare"},
	'rod of lordly might': {"name":"Rod of Lordly Might","id":"rod of lordly might","magic_item":true,"requires_attunement":true,"type":"Rod","rarity":"legendary"},
	'rod of rulership': {"name":"Rod of Rulership","id":"rod of rulership","magic_item":true,"requires_attunement":true,"type":"Rod","rarity":"rare"},
	'rod of security': {"name":"Rod of Security","id":"rod of security","magic_item":true,"requires_attunement":false,"type":"Rod","rarity":"very rare"},
	'rope of climbing': {"name":"Rope of Climbing","id":"rope of climbing","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'rope of entanglement': {"name":"Rope of Entanglement","id":"rope of entanglement","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'scarab of protection': {"name":"Scarab of Protection","id":"scarab of protection","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"legendary"},
	'slippers of spider climbing': {"name":"Slippers of Spider Climbing","id":"slippers of spider climbing","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'sovereign glue': {"name":"Sovereign Glue","id":"sovereign glue","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"legendary"},
	'sphere of annihilation': {"name":"Sphere of Annihilation","id":"sphere of annihilation","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"legendary"},
	'staff of charming': {"name":"Staff of Charming","id":"staff of charming","magic_item":true,"requires_attunement":"bard, cleric, druid, sorcerer, warlock, or wizard","type":"Staff","rarity":"rare"},
	'staff of fire': {"name":"Staff of Fire","id":"staff of fire","magic_item":true,"requires_attunement":"druid, sorcerer, warlock, or wizard","type":"Staff","rarity":"very rare"},
	'staff of frost': {"name":"Staff of Frost","id":"staff of frost","magic_item":true,"requires_attunement":"druid, sorcerer, warlock, or wizard","type":"Staff","rarity":"very rare"},
	'staff of healing': {"name":"Staff of Healing","id":"staff of healing","magic_item":true,"requires_attunement":"bard, cleric, or druid","type":"Staff","rarity":"rare"},
	'staff of power': {"name":"Staff of Power","id":"staff of power","magic_item":true,"requires_attunement":"sorcerer, warlock, or wizard","type":"Staff","rarity":"very rare"},
	'staff of striking': {"name":"Staff of Striking","id":"staff of striking","magic_item":true,"requires_attunement":true,"type":"Staff","rarity":"very rare"},
	'staff of swarming insects': {"name":"Staff of Swarming Insects","id":"staff of swarming insects","magic_item":true,"requires_attunement":"bard, cleric, druid, sorcerer, warlock, or wizard","type":"Staff","rarity":"rare"},
	'staff of the magi': {"name":"Staff of the Magi","id":"staff of the magi","magic_item":true,"requires_attunement":"sorcerer, warlock, or wizard","type":"Staff","rarity":"legendary"},
	'staff of the python': {"name":"Staff of the Python","id":"staff of the python","magic_item":true,"requires_attunement":"cleric, druid, or warlock","type":"Staff","rarity":"uncommon"},
	'staff of the woodlands': {"name":"Staff of the Woodlands","id":"staff of the woodlands","magic_item":true,"requires_attunement":"druid","type":"Staff","rarity":"rare"},
	'staff of thunder and lightning': {"name":"Staff of Thunder and Lightning","id":"staff of thunder and lightning","magic_item":true,"requires_attunement":true,"type":"Staff","rarity":"very rare"},
	'staff of withering': {"name":"Staff of Withering","id":"staff of withering","magic_item":true,"requires_attunement":"cleric, druid, or warlock","type":"Staff","rarity":"rare"},
	'stone of controlling earth elementals': {"name":"Stone of Controlling Earth Elementals","id":"stone of controlling earth elementals","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"rare"},
	'stone of good luck (luckstone)': {"name":"Stone of Good Luck (Luckstone)","id":"stone of good luck (luckstone)","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'talisman of pure good': {"name":"Talisman of Pure Good","id":"talisman of pure good","magic_item":true,"requires_attunement":"creature of good alignment","type":"Wondrous item","rarity":"legendary"},
	'talisman of the sphere': {"name":"Talisman of the Sphere","id":"talisman of the sphere","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"legendary"},
	'talisman of ultimate evil': {"name":"Talisman of Ultimate Evil","id":"talisman of ultimate evil","magic_item":true,"requires_attunement":"creature of evil alignment","type":"Wondrous item","rarity":"legendary"},
	'tome of clear thought': {"name":"Tome of Clear Thought","id":"tome of clear thought","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'tome of leadership and influence': {"name":"Tome of Leadership and Influence","id":"tome of leadership and influence","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'tome of understanding': {"name":"Tome of Understanding","id":"tome of understanding","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"very rare"},
	'universal solvent': {"name":"Universal Solvent","id":"universal solvent","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"legendary"},
	'wand of binding': {"name":"Wand of Binding","id":"wand of binding","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"rare"},
	'wand of enemy detection': {"name":"Wand of Enemy Detection","id":"wand of enemy detection","magic_item":true,"requires_attunement":true,"type":"Wand","rarity":"rare"},
	'wand of fear': {"name":"Wand of Fear","id":"wand of fear","magic_item":true,"requires_attunement":true,"type":"Wand","rarity":"rare"},
	'wand of fireballs': {"name":"Wand of Fireballs","id":"wand of fireballs","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"rare"},
	'wand of lightning bolts': {"name":"Wand of Lightning Bolts","id":"wand of lightning bolts","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"rare"},
	'wand of magic detection': {"name":"Wand of Magic Detection","id":"wand of magic detection","magic_item":true,"requires_attunement":false,"type":"Wand","rarity":"uncommon"},
	'wand of magic missiles': {"name":"Wand of Magic Missiles","id":"wand of magic missiles","magic_item":true,"requires_attunement":false,"type":"Wand","rarity":"uncommon"},
	'wand of paralysis': {"name":"Wand of Paralysis","id":"wand of paralysis","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"rare"},
	'wand of polymorph': {"name":"Wand of Polymorph","id":"wand of polymorph","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"very rare"},
	'wand of secrets': {"name":"Wand of Secrets","id":"wand of secrets","magic_item":true,"requires_attunement":false,"type":"Wand","rarity":"uncommon"},
	'wand of the war mage, +1': {"name":"Wand of the War Mage, +1","id":"wand of the war mage, +1","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"uncommon"},
	'wand of the war mage, +2': {"name":"Wand of the War Mage, +2","id":"wand of the war mage, +2","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"rare"},
	'wand of the war mage, +3': {"name":"Wand of the War Mage, +3","id":"wand of the war mage, +3","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"very rare"},
	'wand of web': {"name":"Wand of Web","id":"wand of web","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"uncommon"},
	'wand of wonder': {"name":"Wand of Wonder","id":"wand of wonder","magic_item":true,"requires_attunement":"spellcaster","type":"Wand","rarity":"rare"},
	'well of many worlds': {"name":"Well of Many Worlds","id":"well of many worlds","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"legendary"},
	'wind fan': {"name":"Wind Fan","id":"wind fan","magic_item":true,"requires_attunement":false,"type":"Wondrous item","rarity":"uncommon"},
	'winged boots': {"name":"Winged Boots","id":"winged boots","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"uncommon"},
	'wings of flying': {"name":"Wings of Flying","id":"wings of flying","magic_item":true,"requires_attunement":true,"type":"Wondrous item","rarity":"rare"},
	
	// common magic items from xanathar's guide:
	"armor of gleaming": {"name":"Armor Of Gleaming","id":"armor of gleaming","type":"Armor (any medium or heavy)","rarity":"common","magic_item":true},
	"bead or nourishment": {"name":"Bead Or Nourishment","id":"bead or nourishment","type":"Wondrous item","rarity":"common","magic_item":true},
	"bead of refreshment": {"name":"Bead Of Refreshment","id":"bead of refreshment","type":"Wondrous item","rarity":"common","magic_item":true},
	"boots of false tracks": {"name":"Boots Of False Tracks","id":"boots of false tracks","type":"Wondrous item","rarity":"common","magic_item":true},
	"candle of the deep": {"name":"Candle Of The Deep","id":"candle of the deep","type":"Wondrous item","rarity":"common","magic_item":true},
	"castoff armor": {"name":"Cast-Off Armor","id":"castoff armor","type":"Armor (light. medium. or heavy)","rarity":"common","magic_item":true},
	"charlatans die": {"name":"Charlatan's Die","id":"charlatans die","type":"Wondrous item","rarity":"common", requires_attunement:true, "magic_item":true},
	"cloak of billowing": {"name":"Cloak Of Billowing","id":"cloak of billowing","type":"Wondrous item","rarity":"common","magic_item":true},
	"cloak of many fashions": {"name":"Cloak Of Many Fashions","id":"cloak of many fashions","type":"Wondrous item","rarity":"common","magic_item":true},
	"clockwork amulet": {"name":"Clockwork Amulet","id":"clockwork amulet","type":"Wondrous item","rarity":"common","magic_item":true},
	"clothes of mending": {"name":"Clothes Of Mending","id":"clothes of mending","type":"Wondrous item","rarity":"common","magic_item":true},
	"dark shard amulet": {"name":"Dark Shard Amulet","id":"dark shard amulet","type":"Wondrous item","rarity":"common", requires_attunement: "warlock","magic_item":true},
	"dread helm": {"name":"Dread Helm","id":"dread helm","type":"Wondrous item","rarity":"common","magic_item":true},
	"ear horn of hearing": {"name":"Ear Horn Of Hearing","id":"ear horn of hearing","type":"Wondrous item","rarity":"common","magic_item":true},
	"enduring spellbook": {"name":"Enduring Spellbook","id":"enduring spellbook","type":"Wondrous item","rarity":"common","magic_item":true},
	"ersatz eye": {"name":"Ersatz Eye","id":"ersatz eye","type":"Wondrous item","rarity":"common", requires_attunement: true,"magic_item":true},
	"hat of vermin": {"name":"Hat Of Vermin","id":"hat of vermin","type":"Wondrous item","rarity":"common","magic_item":true},
	"hat of wizardry": {"name":"Hat Of Wizardry","id":"hat of wizardry","type":"Wondrous item","rarity":"common", requires_attunement:'wizard', "magic_item":true},
	"hewards handy spice pouch": {"name":"Heward's Handy Spice Pouch","id":"hewards handy spice pouch","type":"Wondrous item","rarity":"common","magic_item":true},
	"horn of silent alarm": {"name":"Horn Of Silent Alarm","id":"horn of silent alarm","type":"Wondrous item","rarity":"common","magic_item":true},
	"instrument of illusions": {"name":"Instrument Of Illusions","id":"instrument of illusions","type":"Wondrous item","rarity":"common", requires_attunement: true,"magic_item":true},
	"instrument of scribing": {"name":"Instrument Of Scribing","id":"instrument of scribing","type":"Wondrous item","rarity":"common", requires_attunement: true,"magic_item":true},
	"lock of trickery": {"name":"Lock Of Trickery","id":"lock of trickery","type":"Wondrous item","rarity":"common","magic_item":true},
	"moontouched sword": {"name":"Moon-Touched Sword","id":"moontouched sword","type":"Weapon (any sword)","rarity":"common","magic_item":true},
	"mystery key": {"name":"Mystery Key","id":"mystery key","type":"Wondrous item","rarity":"common","magic_item":true},
	"orb of direction": {"name":"Orb Of Direction","id":"orb of direction","type":"Wondrous item","rarity":"common","magic_item":true},
	"orb of time": {"name":"Orb Of Time","id":"orb of time","type":"Wondrous item","rarity":"common","magic_item":true},
	"perfume of bewitching": {"name":"Perfume Of Bewitching","id":"perfume of bewitching","type":"Wondrous item","rarity":"common","magic_item":true},
	"pipe of smoke monsters": {"name":"Pipe Of Smoke Monsters","id":"pipe of smoke monsters","type":"Wondrous item","rarity":"common","magic_item":true},
	"pole of angling": {"name":"Pole Of Angling","id":"pole of angling","type":"Wondrous item","rarity":"common","magic_item":true},
	"pole of collapsing": {"name":"Pole Of Collapsing","id":"pole of collapsing","type":"Wondrous item","rarity":"common","magic_item":true},
	"pot of awakening": {"name":"Pot Of Awakening","id":"pot of awakening","type":"Wondrous item","rarity":"common","magic_item":true},
	"rope of mending": {"name":"Rope Of Mending","id":"rope of mending","type":"Wondrous item","rarity":"common","magic_item":true},
	"ruby of the war mage": {"name":"Ruby Of The War Mage","id":"ruby of the war mage","type":"Wondrous item","rarity":"common", requires_attunement: 'spellcaster',"magic_item":true},
	"shield of expression": {"name":"Shield Of Expression","id":"shield of expression","type":"Armor (shie1d)","rarity":"common","magic_item":true},
	"smoldering armor": {"name":"Smoldering Armor","id":"smoldering armor","type":"Armor (any)","rarity":"common","magic_item":true},
	"staff of adornment": {"name":"Staff Of Adornment","id":"staff of adornment","type":"Staff","rarity":"common","magic_item":true},
	"staff of birdcalls": {"name":"Staff Of Birdcalls","id":"staff of birdcalls","type":"Staff","rarity":"common","magic_item":true},
	"staff of flowers": {"name":"Staff Of Flowers","id":"staff of flowers","type":"Staff","rarity":"common","magic_item":true},
	"talking doll": {"name":"Talking Doll","id":"talking doll","type":"Wondrous item","rarity":"common", requires_attunement: true,"magic_item":true},
	"tankard of sobriety": {"name":"Tankard Of Sobriety","id":"tankard of sobriety","type":"Wondrous item","rarity":"common","magic_item":true},
	"unbreakable arrow": {"name":"Unbreakable Arrow","id":"unbreakable arrow","type":"Weapon (arrow)","rarity":"common","magic_item":true},
	"veterans cane": {"name":"Veteran'S Cane","id":"veterans cane","type":"Wondrous item","rarity":"common","magic_item":true},
	"walloping ammunition": {"name":"Walloping Ammunition","id":"walloping ammunition","type":"Weapon (any ammunition)","rarity":"common","magic_item":true},
	"wand of conducting": {"name":"Wand Of Conducting","id":"wand of conducting","type":"Wand","rarity":"common","magic_item":true},
	"wand of pyrotechnics": {"name":"Wand Of Pyrotechnics","id":"wand of pyrotechnics","type":"Wand","rarity":"common","magic_item":true},
	"wand of scowls": {"name":"Wand Of Scowls","id":"wand of scowls","type":"Wand","rarity":"common","magic_item":true},
	"wand of smiles": {"name":"Wand Of Smiles","id":"wand of smiles","type":"Wand","rarity":"common","magic_item":true},
};

module.exports.item_desc = {
	'acid': 'As an action, you can splash the contents of this vial onto a creature within 5 feet of you or throw the vial up to 20 feet, shattering it on impact. In either case, make a ranged attack against a creature or object, treating the acid as an improvised weapon. On a hit, the target takes 2d6 acid damage.',
	'alchemists fire': 'This sticky, adhesive fluid ignites when exposed to air. As an action, you can throw this flask up to 20 feet, shattering it on impact. Make a ranged attack against a creature or object, treating the alchemist\'s fire as an improvised weapon. On a hit, the target takes 1d4 fire damage at the start of each of its turns. A creature can end this damage by using its action to make a DC 10 Dexterity check to extinguish the flames.',
	'antitoxin': 'A creature that drinks this vial of liquid gains advantage on saving throws against poison for 1 hour. It confers no benefit to undead or constructs.',
	'arcane focus, crystal': 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.',
	'arcane focus, orb': 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.',
	'arcane focus, rod': 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.',
	'arcane focus, staff': 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.',
	'arcane focus, wand': 'An arcane focus is a special item--an orb, a crystal, a rod, a specially constructed staff, a wand-like length of wood, or some similar item--designed to channel the power of arcane spells. A sorcerer, warlock, or wizard can use such an item as a spellcasting focus.',
	'ball bearings': 'As an action, you can spill these tiny metal balls from their pouch to cover a level, square area that is 10 feet on a side. A creature moving across the covered area must succeed on a DC 10 Dexterity saving throw or fall prone. A creature moving through the area at half speed doesn\'t need to make the save.',
	'block and tackle': 'A set of pulleys with a cable threaded through them and a hook to attach to objects, a block and tackle allows you to hoist up to four times the weight you can normally lift.',
	'book': 'A book might contain poetry, historical accounts, information pertaining to a particular field of lore, diagrams and notes on gnomish contraptions, or just about anything else that can be represented using text or pictures. A book of spells is a spellbook (described later in this section).',
	'caltrops': 'As an action, you can spread a bag of caltrops to cover a square area that is 5 feet on a side. Any creature that enters the area must succeed on a DC 15 Dexterity saving throw or stop moving this turn and take 1 piercing damage. Taking this damage reduces the creature\'s walking speed by 10 feet until the creature regains at least 1 hit point. A creature moving through the area at half speed doesn\'t need to make the save.',
	'candle': 'For 1 hour, a candle sheds bright light in a 5-foot radius and dim light for an additional 5 feet.',
	'case, crossbow bolt': 'This wooden case can hold up to twenty crossbow bolts.',
	'case, map or scroll': 'This cylindrical leather case can hold up to ten rolled-up sheets of paper or five rolled-up sheets of parchment.',
	'chain': 'A chain has 10 hit points. It can be burst with a successful DC 20 Strength check.',
	'climbers kit': 'A climber\'s kit includes special pitons, boot tips, gloves, and a harness. You can use the climber\'s kit as an action to anchor yourself; when you do, you can\'t fall more than 25 feet from the point where you anchored yourself, and you can\'t climb more than 25 feet away from that point without undoing the anchor.',
	'component pouch': 'A component pouch is a small, watertight leather belt pouch that has compartments to hold all the material components and other special items you need to cast your spells, except for those components that have a specific cost (as indicated in a spell\'s description).',
	'crowbar': 'Using a crowbar grants advantage to Strength checks where the crowbar\'s leverage can be applied.',
	'druidic focus, sprig of mistletoe': 'A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals. A druid can use such an object as a spellcasting focus.',
	'druidic focus, totem': 'A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals. A druid can use such an object as a spellcasting focus.',
	'druidic focus, wooden staff': 'A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals. A druid can use such an object as a spellcasting focus.',
	'druidic focus, yew wand': 'A druidic focus might be a sprig of mistletoe or holly, a wand or scepter made of yew or another special wood, a staff drawn whole out of a living tree, or a totem object incorporating feathers, fur, bones, and teeth from sacred animals. A druid can use such an object as a spellcasting focus.',
	'fishing tackle': 'This kit includes a wooden rod, silken line, corkwood bobbers, steel hooks, lead sinkers, velvet lures, and narrow netting.',
	'healers kit': 'This kit is a leather pouch containing bandages, salves, and splints. The kit has ten uses. As an action, you can expend one use of the kit to stabilize a creature that has 0 hit points, without needing to make a Wisdom (Medicine) check.',
	'holy symbol, amulet': 'A holy symbol is a representation of a god or pantheon. It might be an amulet depicting a symbol representing a deity, the same symbol carefully engraved or inlaid as an emblem on a shield, or a tiny box holding a fragment of a sacred relic. A cleric or paladin can use a holy symbol as a spellcasting focus. To use the symbol in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield.',
	'holy symbol, emblem': 'A holy symbol is a representation of a god or pantheon. It might be an amulet depicting a symbol representing a deity, the same symbol carefully engraved or inlaid as an emblem on a shield, or a tiny box holding a fragment of a sacred relic. A cleric or paladin can use a holy symbol as a spellcasting focus. To use the symbol in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield.',
	'holy symbol, reliquary': 'A holy symbol is a representation of a god or pantheon. It might be an amulet depicting a symbol representing a deity, the same symbol carefully engraved or inlaid as an emblem on a shield, or a tiny box holding a fragment of a sacred relic. A cleric or paladin can use a holy symbol as a spellcasting focus. To use the symbol in this way, the caster must hold it in hand, wear it visibly, or bear it on a shield.',
	'holy water': 'As an action, you can splash the contents of this flask onto a creature within 5 feet of you or throw it up to 20 feet, shattering it on impact. In either case, make a ranged attack against a target creature, treating the holy water as an improvised weapon. If the target is a fiend or undead, it takes 2d6 radiant damage. A cleric or paladin may create holy water by performing a special ritual. The ritual takes 1 hour to perform, uses 25 gp worth of powdered silver, and requires the caster to expend a 1st-level spell slot.',
	'hunting trap': 'When you use your action to set it, this trap forms a saw-toothed steel ring that snaps shut when a creature steps on a pressure plate in the center. The trap is affixed by a heavy chain to an immobile object, such as a tree or a spike driven into the ground. A creature that steps on the plate must succeed on a DC 13 Dexterity saving throw or take 1d4 piercing damage and stop moving. Thereafter, until the creature breaks free of the trap, its movement is limited by the length of the chain (typically 3 feet long). A creature can use its action to make a DC 13 Strength check, freeing itself or another creature within its reach on a success. Each failed check deals 1 piercing damage to the trapped creature.',
	'lamp': 'A lamp casts bright light in a 15-foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil.',
	'lantern, bullseye': 'A bullseye lantern casts bright light in a 60-foot cone and dim light for an additional 60 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil.',
	'lantern, hooded': 'A hooded lantern casts bright light in a 30-foot radius and dim light for an additional 30 feet. Once lit, it burns for 6 hours on a flask (1 pint) of oil. As an action, you can lower the hood, reducing the light to dim light in a 5-foot radius.',
	'lock': 'A key is provided with the lock. Without the key, a creature proficient with thieves\' tools can pick this lock with a successful DC 15 Dexterity check. Your DM may decide that better locks are available for higher prices.',
	'magnifying glass': 'This lens allows a closer look at small objects. It is also useful as a substitute for flint and steel when starting fires. Lighting a fire with a magnifying glass requires light as bright as sunlight to focus, tinder to ignite, and about 5 minutes for the fire to ignite. A magnifying glass grants advantage on any ability check made to appraise or inspect an item that is small or highly detailed.',
	'manacles': 'These metal restraints can bind a Small or Medium creature. Escaping the manacles requires a successful DC 20 Dexterity check. Breaking them requires a successful DC 20 Strength check. Each set of manacles comes with one key. Without the key, a creature proficient with thieves\' tools can pick the manacles\' lock with a successful DC 15 Dexterity check. Manacles have 15 hit points.',
	'mess kit': 'This tin box contains a cup and simple cutlery. The box clamps together, and one side can be used as a cooking pan and the other as a plate or shallow bowl.',
	'oil': 'Oil usually comes in a clay flask that holds 1 pint. As an action, you can splash the oil in this flask onto a creature within 5 feet of you or throw it up to 20 feet, shattering it on impact. Make a ranged attack against a target creature or object, treating the oil as an improvised weapon. On a hit, the target is covered in oil. If the target takes any fire damage before the oil dries (after 1 minute), the target takes an additional 5 fire damage from the burning oil. You can also pour a flask of oil on the ground to cover a 5-foot-square area, provided that the surface is level. If lit, the oil burns for 2 rounds and deals 5 fire damage to any creature that enters the area or ends its turn in the area. A creature can take this damage only once per turn.',
	'poison, basic': 'You can use the poison in this vial to coat one slashing or piercing weapon or up to three pieces of ammunition. Applying the poison takes an action. A creature hit by the poisoned weapon or ammunition must make a DC 10 Constitution saving throw or take 1d4 poison damage. Once applied, the poison retains potency for 1 minute before drying.',
	'potion of healing': 'A character who drinks the magical red fluid in this vial regains 2d4 + 2 hit points. Drinking or administering a potion takes an action.',
	'pouch': 'A cloth or leather pouch can hold up to 20 sling bullets or 50 blowgun needles, among other things. A compartmentalized pouch for holding spell components is called a component pouch (described earlier in this section).',
	'quiver': 'A quiver can hold up to 20 arrows.',
	'ram, portable': 'You can use a portable ram to break down doors. When doing so, you gain a +4 bonus on the Strength check. One other character can help you use the ram, giving you advantage on this check.',
	'rations': 'Rations consist of dry foods suitable for extended travel, including jerky, dried fruit, hardtack, and nuts.',
	'rope': 'Rope, whether made of hemp or silk, has 2 hit points and can be burst with a DC 17 Strength check.',
	'scale, merchants': 'A scale includes a small balance, pans, and a suitable assortment of weights up to 2 pounds. With it, you can measure the exact weight of small objects, such as raw precious metals or trade goods, to help determine their worth.',
	'spellbook': 'Essential for wizards, a spellbook is a leather-bound tome with 100 blank vellum pages suitable for recording spells.',
	'spyglass': 'Objects viewed through a spyglass are magnified to twice their size.',
	'tent': 'A simple and portable canvas shelter, a tent sleeps two.',
	'tinderbox': 'This small container holds flint, fire steel, and tinder (usually dry cloth soaked in light oil) used to kindle a fire. Using it to light a torch--or anything else with abundant, exposed fuel--takes an action. Lighting any other fire takes 1 minute.',
	'torch': 'A torch burns for 1 hour, providing bright light in a 20-foot radius and dim light for an additional 20 feet. If you make a melee attack with a burning torch and hit, it deals 1 fire damage.',

	'saddle, riding': "A military saddle braces the rider, helping you keep your seat on an active mount in battle. It gives you advantage on any check you make to remain mounted. An exotic saddle is required for riding any aquatic or flying mount.",
	'saddle, military': "A military saddle braces the rider, helping you keep your seat on an active mount in battle. It gives you advantage on any check you make to remain mounted. An exotic saddle is required for riding any aquatic or flying mount.",
	'saddle, exotic': "A military saddle braces the rider, helping you keep your seat on an active mount in battle. It gives you advantage on any check you make to remain mounted. An exotic saddle is required for riding any aquatic or flying mount.",
	'saddle, pack': "A military saddle braces the rider, helping you keep your seat on an active mount in battle. It gives you advantage on any check you make to remain mounted. An exotic saddle is required for riding any aquatic or flying mount.",
};

module.exports.minor_item_list = [
	'armor of gleaming',
	'bead of nourishment',
	'bead of refreshment',
	'boots of false tracks',
	'candle of the deep',
	'cast off armor',
	'charlatans die',
	'cloak of billowing',
	'cloak of many fashions',
	'clockwork amulet',
	'clothes of mending',
	'dark shard amulet',
	'dread helm',
	'ear horn of hearing',
	'enduring spellbook',
	'ersatz eye',
	'hat of vermin',
	'hat of wizardry',
	'hewards handy spice pouch',
	'horn of silent alarm',
	'instrument of illusions',
	'instrument of scribing',
	'lock of trickery',
	'moon-touched sword',
	'mystery key',
	'orb of direction',
	'orb of time',
	'perfume of bewitching',
	'pipe of smoke monsters',
	'pole of angling',
	'pole of collapsing',
	'pot of awakening',
	'potion of climbing',
	'potion of healing',
	'rope of mending',
	'ruby of the war mage',
	'shield of expression',
	'smoldering armor',
	'spell scroll (cantrip)',
	'spell scroll (lst level)',
	'staff of adornment',
	'staff of birdcalls',
	'staff of flowers',
	'talking doll',
	'tankard of sobriety',
	'unbreakable arrow',
	'veterans cane',
	'walloping ammunition',
	'wand of conducting',
	'wand of pyrotechnics',
	'wand of scowls',
	'wand of smiles',
	'alchemy jug',  // missing
	'ammunition, +1',
	'bag of holding',
	'cap of water breathing',  // missing
	'cloak of the manta ray',
	'decanter of endless water',
	'driftglobe',  // missing
	'dust of disappearance',
	'dust of dryness',
	'dust of sneezing and choking',
	'elemental gem',
	'eyes of minute seeing',
	'goggles of night',
	'helm of comprehending languages',
	'immovable rod',
	'keoghtoms ointment',  // missing
	'lantern of revealing',
	'mariners armor',
	'mithral armor',  // missing
	'oil of slipperiness',
	'periapt of health',
	'philter of love',
	'potion of animal friendship',
	'potion of fire breath', // missing
	'potion of greater healing',
	'potion of growth',
	'potion of hill giant strength',
	'potion of poison',
	'potion of resistance',
	'potion of water breathing',
	'ring of swimming',
	'robe of useful items',
	'rope of climbing',
	'saddle of the cavalier',
	'sending stones', // missing
	'spell scroll (2nd level)',
	'spell scroll (3rd level)',
	'wand of magic detection',
	'wand of secrets',
	'ammunition, +2',
	'bag of beans',
	'bead of force',
	'chime of opening',
	'elixir of health', // missing
	'folding boat',
	'handy haversack',
	'horseshoes of speed',
	'necklace of fireballs',
	'oil of etherealness',
	'portable hole',
	'potion of clairvoyance',
	'potion of diminution',
	'potion of fire giant strength',
	'potion of frost giant strength',
	'potion of gaseous form',
	'potion of heroism',
	'potion of invulnerabulllty',
	'potion of mind reading',
	'potion of stone giant strength',
	'potion of superior healing',
	'feather token',
	'scroll of protectlon',
	'spell scroll (4th level)',
	'spell scroll (5th level)',
	'ammunition, +3',
	'arrow of slaying',
	'bag of devouring',
	'horseshoes of a zephyr',
	'marvelous pigments',
	'oil of sharpness',
	'potion of cloud giant strength',
	'potion of flying',
	'potion of invisibility',
	'potion of longevity',
	'potion of speed',
	'potion of supreme healing',
	'potion of vitality',
	'spell scroll (6th level)',
	'spell scroll (7th level)',
	'spell scroll (8th level)',
	'potion of storm giant strength',
	'sovereign glue',
	'spell scroll (9th level)',
	'universal solvent',
];


module.exports.standard_awards = {
	//                   Tier
	minor: {//       1,  2, 3, 4
		'common':   [6, 10, 3, 0],
		'uncommon': [2, 12, 6, 0],
		'rare':     [1,  5, 9, 4],
		'very rare':[0,  1, 5, 9],
		'legendary':[0,  0, 1, 6],
	},
	major: {
		'common':   [0,  0, 0, 0],
		'uncommon': [2,  5, 1, 0],
		'rare':     [0,  1, 2, 1],
		'very rare':[0,  0, 2, 2],
		'legendary':[0,  0, 1, 3],
	},
};
